package com.modtion.fightcovid.utils

import com.modtion.fightcovid.model.Hospital
import java.util.*
import kotlin.collections.ArrayList

class HospitalData {

    fun getHistoryList(city:String) : List<Hospital>{
        val list =  ArrayList<Hospital> ()

        when(city) {
            "Aceh" -> {
                list.add(Hospital("Rumkit Tk II Banda Aceh","Alamat Jl. T. Angkasa Bendahara, Kuta Alam, Kec. Kuta Alam, Kota Banda Aceh, Aceh 24415","Telepon (0651) 24712"))
                list.add(Hospital("RSU Dr. Zainoel Abidin Banda Aceh","Alamat Jl. Tgk. Daud Beureuh No. 108, Banda Aceh","Telepon (0651) 34562"))
                list.add(Hospital("Rumkit TK IV Meulaboh","Alamat Suwak Indrapuri, Johan Pahlawan, Kabupaten Aceh Barat, Aceh 23681", ""))
                list.add(Hospital("Rumkit Tk. IV LHokseumawe","Alamat JL. Samudera, Hagu Sel., Banda Sakti, Kota Lhokseumawe, Aceh","Telepon (0645) 40300"))
                list.add(Hospital("RSU Cut Meutia Lhokseumawe","Alamat Jl. Banda Aceh Medan KM 5 Buket Rata, Lhokseumawe","Telepon (0645) 46334"))
            }
            "Sumatera Utara" -> {
                list.add(Hospital("RSAL-3 KOMANG MAKES","Alamat Jl. Bengkalis No.1, Belawan I, Medan Kota Belawan, Kota Medan, Sumatera Utara 20411","Telepon (061) 6941741"))
                list.add(Hospital("Rumkit Tk.IV/Binjai","Alamat Jl. Bandung, Rambung Barat no 4 Binjai Selatan, Kota Binjai, Sumatera Utara 20735","Telepon (061) 8827705"))
                list.add(Hospital("Rumkit Tk. II/ Putri Hijau Medan","Alamat Jl. Putri Hijau No.17, Kesawan, Kec. Medan Bar., Kota Medan, Sumatera Utara 20111","Telepon (061) 4553900"))
                list.add(Hospital("Tk II Medan","Alamat Jl. K.H. Wahid Hasyim No.1, Merdeka, Kec. Medan Baru, Kota Medan, Sumatera Utara 20222","Telepon (061) 8215990"))
                list.add(Hospital("RSAU-4 DR. ABDUL MALIK LANUD SWO","Alamat Jl. Imam Bonjol No.50, Suka Damai, Kec. Medan Polonia, Kota Medan, Sumatera Utara 20157","Telepon (061) 4572323"))
                list.add(Hospital("RSU H. Adam Malik Medan","Alamat Jl. Bunga Lau No. 17","Telepon (061) 8360051"))
                list.add(Hospital("Tk III Tebing Tinggi","Alamat Jl. Pahlawan No.17, Rambung, Kec. Tebing Tinggi Kota, Kota Tebing Tinggi, Sumatera Utara 20631","Telepon (0621) 326701"))
                list.add(Hospital("RSU Kabanjahe","Alamat Jl. Selamat Ketaren, Lau Cimba, Kabanjahe, Kabupaten Karo, Sumatera Utara 22111","Telepon (0628) 20012"))
                list.add(Hospital("Rumkit Tk. IV/Pematang Siantar","Alamat Jl. Gunung Simanuk Manuk No.6, Timbang Galung, Kec. Siantar Bar., Kota Pematang Siantar, Sumatera Utara 21143",""))
                list.add(Hospital("RSUD Dr. Djasamen Saragih","Alamat Jl. Sutomo No. 230, Pematang Sianta","Telepon (0622) 22959"))
                list.add(Hospital("RSU Tarutung","Alamat Jl. Agus Salim No.1 Tarutung, Kab. Tapanuli Utara","Telepon (0633) 21303 , 20450"))
                list.add(Hospital("Rumkit Tk. IV/Padang Sidempuan","Alamat Jl. Padang Sidempuan, Losung Batu, Padangsidimpuan Utara, Kota Padang Sidempuan, Sumatera Utara 22733",""))
                list.add(Hospital("RSU Padang Sidempuan","Alamat Jl. Dr. FL Tobing, Padang Sidempuan","Telepon 0634 21780 Fax: 0634 21251"))
            }
            "Sumatera Barat" -> {
                list.add(Hospital("RSU Dr. Achmad Mochtar","Alamat Jl. Dr. A. Rivai, Bukittinggi","Telepon 0752 21720"))
                list.add(Hospital("Rumkit Tk.IV/Bukit Tinggi","Alamat Jl. Sudirman, Birugo, Kec. Aur Birugo Tigo Baleh, Kota Bukittinggi, Sumatera Barat 26181","Telepon (0752) 8100746"))
                list.add(Hospital("Rumkit Tk. IV/Solok","Alamat JL. Proklamasi, No. 3, VI Suku, Lubuk Sikarah, Kp. Jawa, Tj. Harapan, Kota Solok, Sumatera Barat 27317","Telepon (0755) 325457"))
                list.add(Hospital("TK III Padang","Alamat Jl. Jati No.1, Jati Baru, Kec. Padang Tim., Kota Padang, Sumatera Barat 25129","Telepon (0751) 22270"))
                list.add(Hospital("Rumkit Tk. III/dr.Reksodiwiryo Padang","Alamat Jl. Dr. Wahidin No.1, Ganting Parak Gadang, Kec. Padang Tim., Kota Padang, Sumatera Barat 25132","Telepon (0751) 31003"))
            }
            "Riau" -> {
                list.add(Hospital("RSU Dumai","Alamat Jl. Tanjung Jati No.4, Dumai","Telepon (0765) 440992"))
                list.add(Hospital("Rumkit Tk. IV/Pekan Baru","Alamat Jl. Kesehatan No.2, Kp. Bandar, Kec. Senapelan, Kota Pekanbaru, Riau 28155","Telepon (0761) 22426"))
                list.add(Hospital("RSU Arifin Ahmad Pekan Baru","Alamat Jl. Diponegoro No. 2, Pekanbaru","Telepon (0761) 23418 , 21618 , 21657"))
                list.add(Hospital("Tk III Pekanbaru","Alamat Jalan RA Kartini No.14, Simpang Empat, Pekanbaru Kota, Simpang Empat, Kec. Pekanbaru Kota, Kota Pekanbaru, Riau 28156","Telepon (0761) 47691"))
                list.add(Hospital("RSAU-3 DR. SUKIRMAN LANUD RSN","Alamat Jl. Adi Sucipto, Sidomulyo Tim., Kec. Marpoyan Damai, Kota Pekanbaru, Riau 28289",""))
                list.add(Hospital("RSU Puri Husada","Alamat Jl. Veteran No. 52, Hilir Tembilahan","Telepon (0768) 24563"))
            }
            "Kepulauan Riau" -> {
                list.add(Hospital("RSUD Muhammad Sani (Kab. Karimun)","Alamat Jl. Soekarno - Hatta No. 1 Tanjung Balai Karimun","Telepon (0777) 327808"))
                list.add(Hospital("RSBP Batam","Alamat Jl. Dr. Ciptomangunkusumo, Sekupang Batam","Telepon (0778) 322046 , 322121"))
                list.add(Hospital("RSUD Embung Fatimah","Alamat Jl. R. Soeprapto. Blok D 1 - 9 Batu Aji Kota Batam","Telepon (0778) 364446"))
                list.add(Hospital("RSAL-2 MIDIATO SURYATANI","Alamat Jl. Ciptadi No.1, Tanjungpinang Kota, Kota Tanjung Pinang, Kepulauan Riau","Telepon (0771) 21428"))
                list.add(Hospital("RSUD Provinsi Kep. Riau Tanjungpinang","Alamat Jl. WR Supratman No. 100, KM 8 Tanjungpinang","Telepon (0771) 7335203"))
                list.add(Hospital("RSAU-3 DR. YUNIATI WISMA RANAI","Alamat Kawasan Bandara AU, Ranai Kota, Bunguran Tim., Kabupaten Natuna, Kepulauan Riau 29783",""))
            }
            "Jambi" -> {
                list.add(Hospital("RSU Raden Mattaher Jambi","Alamat Jl. Letjen. Soeprapto No. 31, Telanaipura, Jambi","Telepon (0741) 61692 , 61694 , 63394 , 62364"))
                list.add(Hospital("Tk III Jambi","Alamat Jl. Raden Mattaher No.3, Rajawali, Jambi, Kota Jambi, Jambi 36361","Telepon (0741) 23246"))
            }
            "Bengkulu" -> {
                list.add(Hospital("RSU Arga Makmur","Alamat Jl. Siti Khadijah No.08 Arga Makmur Kab.Bengkulu Utara","Telepon (0737) 521118"))
                list.add(Hospital("RSUD Hasanuddin Damrah Manna","Alamat Jl. Raya Padang Panjang Manna, Kab.Bengkulu Utara","Telepon 085381637684"))
                list.add(Hospital("Tk III Tjtra Bengkulu","Alamat Jl. Veteran No.2, Ps. Jitra, Kec. Tlk. Segara, Kota Bengkulu, Bengkulu 38113","Telepon (0736) 21553"))
                list.add(Hospital("Rumkit Tk. IV /Bengkulu","Alamat Jl. Zainul Arifin No.27, Tim. Indah, Kec. Singaran Pati, Kota Bengkulu, Bengkulu 38225",""))
                list.add(Hospital("RSU Dr. M. Yunus Bengkulu","Alamat Jl. Bhayangkara Sidomulyo, Bengkulu","Telepon (0736) 52004 , 5111"))
            }
            "Sumatera Selatan" -> {
                list.add(Hospital("Rumkit Tk. IV/Lahat","Alamat Jalan Lintas Pagar Alam-Lahat, Pasar Baru, Kecamatan Lahat, Ps. Baru, Kec. Lahat, Kabupaten Lahat, Sumatera Selatan 31461","Telepon (0731) 326195"))
                list.add(Hospital("Rumkit Tk. IV/dr. Noesmir Baturaja","Alamat Jl. Dr. M. Hatta No.16, Baturaja Lama, Kec. Baturaja Timur, Kabupaten Ogan Komering Ulu, Sumatera Selatan 32125","Telepon (0735) 320123"))
                list.add(Hospital("RSU Kayu Agung","Alamat Jl. Letjen Yusuf Singadekane Kel. Jua-jua Kec.Kayuagung, Kab.Ogan Komering Ilir","Telepon (0712) 323889"))
                list.add(Hospital("RS Dr. Rivai Abdullah","Alamat Jl. Sungai Kundur Kelurahan Mariana Kec. Banyuasin I","Telepon (0711) 7537201"))
                list.add(Hospital("RS Muhammadiyah Palembang","Alamat Jln. Jend Ahmad Yani 13, Ulu Palembang 30263","Telp (0711) 511446"))
                list.add(Hospital("Rumkit Tk. II/dr.A K Gani","Alamat Jl. Dr. Ak. Gani No.1, 19 Ilir, Kec. Bukit Kecil, Kota Palembang, Sumatera Selatan 30113",""))
                list.add(Hospital("Balai Besar Laboratorium Kesehatan Palembang","Alamat Jl. Inspektur Yazid No.2, Sekip Jaya, Kec. Kemuning, Kota Palembang, Sumatera Selatan 30126","Telepon (0711) 352683"))
                list.add(Hospital("RSU Dr. M. Hoesin Palembang","Alamat Jl. Jend. Soedirman Km. 3.5 , Palembang 30126","Telepon (0711) 354088"))
                list.add(Hospital("Tk III Palembang","Alamat Jl. Jend. Sudirman No.km 4, RW.5, Ario Kemuning, Kec. Kemuning, Kota Palembang, Sumatera Selatan","Telepon (0711) 410023"))
                list.add(Hospital("RSUD Siti Fatimah Provinsi Sumatera Selatan","Alamat Jl. Kol. H. Burlian Km 6 Kel. Sukabangun, Kec. Sukarami, Palembang 30151","Telepon (0711) 5718883 , 5718889"))
            }
            "Kepulauan Bangka Belitung" -> {
                list.add(Hospital("RSUD Depati Hamzah","Alamat Jl. Soekarno Hatta, Kel.Bukit Besar, Ke.Girimaya Kota Pangkalpinang","Telepon (0717) 438660"))
                list.add(Hospital("RSUD Dr. H. Marsidi Judono","Alamat Jl. Jend. Sudirman Aik Rayak Km.5,5 Tanjungpandan Kab. Belitung","Telepon (0719) 22190"))
            }
            "Lampung" -> {
                list.add(Hospital("RSU Mayjend HM Ryacudu","Alamat Jl. Jend. Sudirman No. 2, Kotabumi, Lampung Utara 34511","Telepon (0724) 22095"))
                list.add(Hospital("RSUD Dr. H. Bob Bazar,SKM","Alamat Jl. Lettu Rohani No. 14B, Kalianda, Kab.Lampung Selatan","Telepon (0727) 322159"))
                list.add(Hospital("RSUD Jend. Ahmad Yani Metro","Alamat Jl. Jend. A.Yani No.13 Kota Metro Lampung","Telepon (0725) 41820"))
                list.add(Hospital("RS Muhammadiyah Metro - Lampung","Alamat Jl. Soekarno Hatta No. 42 Mulyojati 16B Metro Barat, Kota Metro","Telp (0725) 49490"))
                list.add(Hospital("Tk.III Lampung","Alamat Jl. Pramuka No.88, Rajabasa, Kec. Rajabasa, Kota Bandar Lampung, Lampung","Telepon (0721) 706402"))
                list.add(Hospital("Rumkit Tk. IV/Bandar Lampung","Alamat Jl. Dr. Rivai No.7, Penengahan, Kec. Tj. Karang Pusat, Kota Bandar Lampung, Lampung 35121","Telepon (0721) 703574"))
                list.add(Hospital("RSU Abdul Moeloek","Alamat Jl. Dr. Rivai No. 6, Tj. Karang, Lampung 35112","Telepon (0721) 703312 , 702455"))
            }
            "Banten" -> {
                list.add(Hospital("RSUD Dr. Drajat Prawiranegara","Alamat Jl. Rumah Sakit No. 1, Serang","Telepon 0254 200528"))
                list.add(Hospital("Rumkit Tk. IV/Kencana Serang","Alamat Jalan Jendral Ahmad Yani No. 21-23, Sumurpecung, Serang, Cimuncang, Kec. Serang, Kota Serang, Banten 42117","Telepon (0254) 211554"))
                list.add(Hospital("Rumkit Tk. IV Daan Mogot Tangerang","Alamat Jalan Daan Mogot No.59, Sukarasa, Kecamatan Tangerang, RT.003/RW.004, Sukarasa, Kec. Tangerang, Kota Tangerang, Banten 15111","Telepon (021) 5523551"))
                list.add(Hospital("RSU Kab Tangerang","Alamat Jl. Ahmad Yani No.9, Tangerang","Telepon (021) 5512946 , 5513709 , 5523507"))
            }
            "DKI Jakarta" -> {
                list.add(Hospital("RSUD Cengkareng","Alamat Jl. Kamal Raya Bumi Cengkareng Indah, Cengkareng Timur","Telepon (021) 54372874"))
                list.add(Hospital("Tk III Lemdiklat Polri","Alamat Jl. Ciputat Raya No.40, RT.1/RW.9, Pd. Pinang, Kec. Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12310","Telepon (021) 7650384"))
                list.add(Hospital("RSUP Fatmawati","Alamat Jl. RS Fatmawati Cilandak,Jaksel","Telepon (021) 7501524"))
                list.add(Hospital("RSAL-2. MARINIR CILANDAK","Alamat Jl. Raya Cilandak Kko, RT.3/RW.5, Cilandak Tim., Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12560","Telepon (021) 7805296"))
                list.add(Hospital("RSUD Pasar Minggu","Alamat Jl. TB. Simatupang No.1 Kel.Ragunan, Pasar Minggu, Jakarta Selatan","Telepon (021) 29059999"))
                list.add(Hospital("Rumkit Tk. IV/Cijantung","Alamat Mahoni No.2, RT.4/RW.6, Gedong, Kec. Ps. Rebo, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13760","Telepon (021) 8400535"))
                list.add(Hospital("Rumkit Tk. II/M Ridwan Meuraksa","Alamat Jalan Taman Mini I, RT.4/RW.2, Pinang Ranti, Makasar, RT.4/RW.2, Pinang Ranti, Kec. Makasar, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13560","Telepon (021) 22819465"))
                list.add(Hospital("Rumkit Dik Puskdikkes","Alamat Jalan Raya Bogor No.KM. 24, RT.2/RW.9, Kramat Jati, Kec. Kramat jati, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13510","Telepon (021) 8092358"))
                list.add(Hospital("Tk I R. Said Sukanto","Alamat Jl. Raya Jakarta-Bogor, RT.1/RW.5, Kramat Jati, Kec. Kramat jati, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13510","Telepon (021) 8093288"))
                list.add(Hospital("RSAU-2 DR. ESNAWAN A.","Alamat Jl. Merpati No.2, RW.11, Halim Perdana Kusumah, Kec. Makasar, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13610","Telepon (021) 8019046"))
                list.add(Hospital("RSI Jakarta Pondok Kopi","Alamat Jl. Raya Pondok Kopi , Jakarta Timur , 13460","Telp (021) 29809000 , 8630654"))
                list.add(Hospital("Balai Teknik Kesehatan Lingkungan dan Pengendalian","Alamat Jl. Balai Rakyat No.2, RT.12/RW.1, Cakung Tim., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910","Telepon (021) 46824247"))
                list.add(Hospital("RSAL-2 dr MINTOHARDJO","Alamat Jl. Bendungan Hilir 17 Jakpus","Telepon (021) 5703081"))
                list.add(Hospital("RSU Persahabatan","Alamat Jl. Persahabatan Raya","Telepon 021 489 1708"))
                list.add(Hospital("Lembaga Biologi Molekuler Eijkman","Alamat Jl. Pangeran Diponegoro No.69, RW.5, Kenari, Kec. Senen, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10430","Telepon (021) 3917131"))
                list.add(Hospital("Fakultas Kedokteran Universitas Indonesia","Alamat Jl. Salemba Raya No.6, RW.5, Kenari, Kec. Senen, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10430","Telepon (021) 3160493"))
                list.add(Hospital("Balai Besar Laboratorium Kesehatan Jakarta","Alamat Jl. Percetakan Negara No.23 B, Johar Baru, Kec. Johar Baru, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10560","Telepon (021) 4212524"))
                list.add(Hospital("Laboraturium Kesehatan DKI Jakarta","Alamat Jl. Rawasari Timur V, RT.16/RW.2, Cemp. Putih Tim., Kec. Cemp. Putih, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10510","Telepon (021) 4247404"))
                list.add(Hospital("RSPAD Gatot Subroto","Alamat Jl. Dr.A. Rahman Saleh No. 24, Jakpus","Telepon (021) 3440693"))
                list.add(Hospital("RSI Jakarta Cempaka Putih","Alamat Jl. Cempaka Putih Tengah I No.1, Kel. Cempaka Putih Timur, Kec. Cempaka Putih, Kota Jakarta Pusat, DKI Jakarta 10510","Telp (021) 42801567"))
                list.add(Hospital("RSPI Dr. Sulianti Saroso","Alamat Jl. Baru Sunter Permai Raya, Jakarta 14340","Telepon 021 6506559, Fax: 021 6401411"))
            }
            "Jawa Barat" -> {
                list.add(Hospital("Tk III Brimob Kelapa Dua","Alamat Jl. Komjen.Pol.M.Jasin Jl. Klp. Dua Raya, Pasir Gn. Sel., Kec. Cimanggis, Kota Depok, Jawa Barat 16451","Telepon (021) 87704691"))
                list.add(Hospital("RSAU-3 DR. HASAN TOTO ATS","Alamat Jalan Sarjio No. 1, Atang Senjaya, Kemang, Atang Senjaya, Kec. Kemang, Bogor, Jawa Barat 16310","Telepon (0251) 7535976"))
                list.add(Hospital("Rumkit Tk. IV/Salak Bogor","Alamat Jl. Jend. Sudirman No.8, Sempur, Kecamatan Bogor Tengah, Kota Bogor, Jawa Barat 16121","Telepon (0251) 8345222"))
                list.add(Hospital("RS Paru Dr. M. Goenawan Partowidigdo","Alamat Jl. Raya Puncak KM.83, Po Box 28 Cisarua Bogor","Telepon (0251) 8253630 Fax (0251) 8257662"))
                list.add(Hospital("Tk III Setukpa","Alamat Jl Aminta Azmali Trip No.59A, Sriwidari, Kec. Gunungpuyuh, Kota Sukabumi, Jawa Barat 43121","Telepon (0266) 226262"))
                list.add(Hospital("RSUD R. Syamsudin, SH Kota Sukabumi","Alamat Jl. Rumah Sakit No.1 Kota Sukabumi","Telepon (0266) 225180 , 225181"))
                list.add(Hospital("RSAU-4 DR. HOEDIONO LANUD SDM","Alamat Jl. Pangkalan TNI AU, Suryadarma, Kalijati, Kalijati Barat, Kalijati, Kalijati Bar., Kec. Kalijati, Kabupaten Subang, Jawa Barat 41271",""))
                list.add(Hospital("Tk III Indramayu","Alamat JL. Losarang Raya, KM. 73-75, Losarang, Krimun, Indramayu, Krimun, Kec. Losarang, Kabupaten Indramayu, Jawa Barat 45253","Telepon (0234) 507877"))
                list.add(Hospital("RSU Indramayu","Alamat Jl. Murah Nara No.7 Sindang, Indramayu","Telepon 0234 272655"))
                list.add(Hospital("Rumkit Tk. III/Ciremai Cirebon","Alamat Jl. Kesambi No.237, Drajat, Kec. Kesambi, Kota Cirebon, Jawa Barat 45133","Telepon (0231) 238335"))
                list.add(Hospital("RSU Gunung Jati","Alamat JL. Kosamabi No. 56, Kota Cirebon",""))
                list.add(Hospital("Rumkit Tk. IV/Guntur Garut","Alamat Jl. Bratayuda No.101, Kota Kulon, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44112","Telepon (0262) 232325"))
                list.add(Hospital("RSU Dr. Slamet Garut","Alamat Jl. Rumah Sakit No.12 Kec.Tarogong Kidul, Kab.Garut 44151","Telepon 0262 232720"))
                list.add(Hospital("Rumkit Tk. II/Dustira Cimahi","Alamat Cimahi, Baros, Kec. Cimahi Tengah, Kota Cimahi, Jawa Barat 40521",""))
                list.add(Hospital("RSAU-4 DR. N. LUBIS LANUD SULAIMAN","Alamat Jl. Terusan Kopo-Soreang No.461, Sulaiman, Kec. Margahayu, Bandung, Jawa Barat 40229",""))
                list.add(Hospital("Tk II Bandung","Alamat Jl. Moh. Toha No.369, Ciseureuh, Kec. Regol, Kota Bandung, Jawa Barat 40256","Telepon 0811-2232-056"))
                list.add(Hospital("Rumkit Tk. IV/Sariningsih Bandung","Alamat Jl. L. L. R.E. Martadinata No.9, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40115","Telepon (022) 4211650"))
                list.add(Hospital("RSU Hasan Sadikin Bandung","Alamat Jl. Pasteur No. 38, Bandung","Telepon (022) 2034953-55"))
                list.add(Hospital("RSTP Dr. H.A. Rotinsulu Bandung","Alamat Jl. Bukit Jarian No. 40, Bandung","Telepon (022) 3034446"))
                list.add(Hospital("RSAU-2 DR. M. SALAMUN","Alamat Jl. Ciumbuleuit No.203, Ciumbuleuit, Kec. Cidadap, Kota Bandung, Jawa Barat 40142","Telepon (022) 2032090"))
            }
            "Jawa Tengah" -> {
                list.add(Hospital("RSUD Cilacap","Alamat Cilacap, Tambaksari, Sidanegara, Kec. Cilacap Tengah, Kabupaten Cilacap, Jawa Tengah 53212","Telepon (0282) 533010"))
                list.add(Hospital("RSU Banyumas","Alamat Jl. Rumah Sakit No. 1, Banyumas","Telepon 0281 796031"))
                list.add(Hospital("RSU Prof. Dr. Margono Soekarjo","Alamat Jl. Dr. Gumbreg No. 1, Purwokerto","Telepon 0281 632708"))
                list.add(Hospital("Rumkit Tk. III/Wijaya Kusuma Purwokerto","Alamat Jl. Prof Dr. HR Bunyamin, Glempang, Bancarkembar, Kec. Purwokerto Utara, Kabupaten Banyumas, Jawa Tengah 53121","Telepon (0281) 633062"))
                list.add(Hospital("RSU Dr. H. RM Soeselo W","Alamat Jl. Dr. Sutromo No. 63, Slawi","Telepon 0283 491016"))
                list.add(Hospital("Rumkit Tk. IV/Tegal","Alamat Jl. Raya Pagongan Jl. RS DKT Pagongan, Jetis, Lemahduwur, Kec. Adiwerna, Tegal, Jawa Tengah 52125","Telepon (0283) 351420"))
                list.add(Hospital("RSUD Kardinah Tegal","Alamat Jl. AIP KS Tubun No 2, Kota Tegal 52124","Telepon (0283) 350377 , 350477"))
                list.add(Hospital("RSU Islam Harapan Anda Kota Tegal","Alamat Jl. Ababil No.42, Randugunting, Kec. Tegal Sel., Kota Tegal, Jawa Tengah 52131","Telepon (0283) 358244"))
                list.add(Hospital("RSUD Brebes","Alamat Jl. Jenderal Sudirman No.181, Pangembon, Brebes, Kec. Brebes, Kabupaten Brebes, Jawa Tengah 52212","Telepon (0283) 671431"))
                list.add(Hospital("RSUD dr. Soedirman Kab. Kebumen","Alamat Kenteng, Muktisari, Kec. Kebumen, Kabupaten Kebumen, Jawa Tengah 54317","Telepon (0287) 381101"))
                list.add(Hospital("RSUD dr. R. G. Taroenadibrata Purbalingga","Alamat Purbalingga, Kembaran Kulon, Kec. Purbalingga, Kabupaten Purbalingga, Jawa Tengah 53319","Telepon (0281) 891016"))
                list.add(Hospital("RSUD Hj. Anna Lasmanah Banjarnegara","Alamat Kutabanjarnegara, Kec. Banjarnegara, Banjarnegara, Jawa Tengah","Telepon (0286) 591464"))
                list.add(Hospital("RSUD Kajen Kab. Pekalongan","Alamat Jl. Raya Karanganyar No.36, Mlatensatu, Karangsari, Kec. Karanganyar, Pekalongan, Jawa Tengah 51182","Telepon (0285) 385231"))
                list.add(Hospital("RSUD dr. M Ashari Pemalang","Alamat Jl. Gatot Subroto No.41, Bojongbata, Kec. Pemalang, Kabupaten Pemalang, Jawa Tengah 52319","Telepon (0284) 321614"))
                list.add(Hospital("RSUD Batang","Alamat Jl. Dr.Sutomo No.42, Kauman, Kec. Batang, Kabupaten Batang, Jawa Tengah 51215","Telepon (0285) 4493034"))
                list.add(Hospital("RSUD Bendan Kota Pekalongan","Alamat Jl. Sriwijaya No.2, Bendan, Kec. Pekalongan Bar., Kota Pekalongan, Jawa Tengah 51119","Telepon (0285) 437222"))
                list.add(Hospital("RSUD Kraton Kab. Pekalongan","Alamat Jl. Veteran 31, Pekalongan","Telepon (0285) 423225 , 423523"))
                list.add(Hospital("RSUD dr. Tjitrowardojo Purworejo","Alamat Doplang, Kec. Purworejo, Kabupaten Purworejo, Jawa Tengah 54114","Telepon (0275) 321118"))
                list.add(Hospital("RS PKU Muhammadiyah Wonosobo","Alamat Jl. Raya Kertek - Wonosobo KM. 4, No. 1, Sudungdewo, Kec. Wonosobo, Kedewan, Jawa Tengah 56371","Telp (0286) 329185 , 085794700150"))
                list.add(Hospital("RSUD Djoyonegoro Temanggung","Alamat Jl. Gajah Mada No.1A, Sendang, Walitelon Sel., Kec. Temanggung, Kab. Temanggung, Jawa Tengah 56229","Telepon (0293) 491119"))
                list.add(Hospital("Rumkit Tk. II/dr.Soedjono Magelang","Alamat Jl. Jend. Urip Sumoharjo No.48, Wates, Kec. Magelang Utara, Kota Magelang, Jawa Tengah 56113","Telepon (0293) 363061"))
                list.add(Hospital("RSUD Tidar Kota","Alamat Jl. Tidar No. 30A, Kota Magelang","Telepon (0293) 362260 , 362463"))
                list.add(Hospital("RS Aisyiyah Muntilan","Alamat Jl. KH.A.Dahlan No 24, Muntilan, Kabupaten magelang, Jawa tengah 56414","Telp (0293) 5891234"))
                list.add(Hospital("RSUD Muntilan Kab. Magelang","Alamat Kartini No.13, Balemulyo, Muntilan, Kec. Muntilan, Magelang, Jawa Tengah 56411","Telepon (0293) 587004"))
                list.add(Hospital("RSI Muhammadiyah Kendal","Alamat Jl. Ar Rahman 17 Weleri - Kendal 51355","Telp (0294) 641870 , 643756"))
                list.add(Hospital("RSU Dr. H. Soewondo","Alamat Jl. Laut 21, Kendal","Telepon 0294 381433"))
                list.add(Hospital("RSUD Tugurejo Semarang","Alamat Jl. Walisongo No. 137 KM 8.5, Jawa Tengah 50185","Telepon (024) 7605297"))
                list.add(Hospital("RSU Colombia Asia Semarang","Alamat Jl. Siliwangi No.143, Kalibanteng Kulon, Kec. Semarang Bar., Kota Semarang, Jawa Tengah 50145","Telepon (024) 7629999"))
                list.add(Hospital("Rumkit Tk. III/Bhakti Wira Tamtama Semarang","Alamat Jl. DR. Sutomo No.17, Barusari, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50245","Telepon (024) 3555944"))
                list.add(Hospital("RSU Dr. Kariadi Semarang","Alamat Jl. Dr.Sutomo No. 16, Semarang","Telepon (024) 8413476"))
                list.add(Hospital("RSU Telogorejo Semarang","Alamat Jl. Kh Ahmad Dahlan, Pekunden, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50134","Telepon (024)86466000"))
                list.add(Hospital("RS PKU Muhammadiyah Roemani Semarang","Alamat Jl Wonodri 22, Semarang, Jawa Tengah 50242","Telp (024) 8444623"))
                list.add(Hospital("RSU St. Elizabeth Semarang","Alamat Jl. Kawi 1, Wonotingal, Kec. Candisari, Kota Semarang, Jawa Tengah 50252","Telepon (024) 8310035"))
                list.add(Hospital("Tk II Semarang","Alamat Jl. Majapahit No.140, Gayamsari, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50248","Telepon (024) 6720675"))
                list.add(Hospital("RSU Sultan Agung Semarang","Alamat Jl. Kaligawe Raya No.KM. 4, Terboyo Kulon, Kec. Genuk, Kota Semarang, Jawa Tengah 50112","Telepon (024) 6580019"))
                list.add(Hospital("RSUD K.R.M.T Wongsonegoro Kota Semarang","Alamat Jl. Fatmawati No.1 Semarang 50272","Telepon (024) 6711500"))
                list.add(Hospital("RSUD Ambarawa","Alamat Jalan R.A. Kartini No. 101 Tambakboyo Lodoyong, Losari, Kec. Ambarawa, Semarang, Jawa Tengah 50611","Telepon (0298) 591020"))
                list.add(Hospital("RSUD Salatiga","Alamat Jl. Osamaliki, Sidorejo Lor, Kec. Sidorejo, Kota Salatiga, Jawa Tengah 50721","Telepon (0298) 324074"))
                list.add(Hospital("Rumkit Tk. IV/Salatiga","Alamat Jl. DR. Muwardi No.50, Kutowinangun Kidul, Kec. Tingkir, Kota Salatiga, Jawa Tengah 50711","Telepon (0298) 326045"))
                list.add(Hospital("RS Paru Dr. Ario Wirawan","Alamat Jl. Hasanudin No.806,Salatiga","Telepon (0298) 326130 , (0298) 322703"))
                list.add(Hospital("RSUD Pandan Arang Boyolali","Alamat Jl. Magelang - Boyolali No.136, Dusun 2, Winong, Kec. Boyolali, Kabupaten Boyolali, Jawa Tengah 57315","Telepon (0276) 321065"))
                list.add(Hospital("RSU Dr Suraji Tirtonegoro","Alamat Jl. Dr. Soeradji T. No. 1, Klaten","Telepon (0272) 321104"))
                list.add(Hospital("RSUD Bagas Waras Klaten","Alamat RT.04/RW.09, Buntalan, Kec. Klaten Tengah, Kabupaten Klaten, Jawa Tengah","Telepon (0272) 3359666"))
                list.add(Hospital("RSU Islam Klaten","Alamat Jl. Klaten - Solo No.KM.4, Sidorejo, Belang Wetan, Kec. Klaten Utara, Kabupaten Klaten, Jawa Tengah","Telepon (0272) 322252"))
                list.add(Hospital("RSUD dr. Soediran MS Wonogiri","Alamat Wonogiri, Joho Lor, Giriwono, Kec. Wonogiri, Kabupaten Wonogiri, Jawa Tengah 57613","Telepon (0273) 321008"))
                list.add(Hospital("RSUD Ir. Soekarno Sukoharjo","Alamat Sukoharjo, Bulusari, Gayam, Kec. Sukoharjo, Kabupaten Sukoharjo, Jawa Tengah 57514","Telepon (0271) 335966"))
                list.add(Hospital("RSUD dr. Soediran MS Wonogiri","Alamat Wonogiri, Joho Lor, Giriwono, Kec. Wonogiri, Kabupaten Wonogiri, Jawa Tengah 57613","Telepon (0273) 321008"))
                list.add(Hospital("RSUD Karanganyar","Alamat Karanganyar, Jengglong, Bejen, Kec. Karanganyar, Kabupaten Karanganyar, Jawa Tengah 57716","Telepon (0271) 495673"))
                list.add(Hospital("RSAU-3 DR. SISWANTO LANUD SMO","Alamat Jl. Tentara Pelajar, Jetak, Malangjiwan, Kec. Colomadu, Kabupaten Karanganyar, Jawa Tengah 57177",""))
                list.add(Hospital("RSUD Karanganyar","Alamat Karanganyar, Jengglong, Bejen, Kec. Karanganyar, Kabupaten Karanganyar, Jawa Tengah 57716","Telepon (0271) 495673"))
                list.add(Hospital("RSUD RA Kartini Jepara","Alamat Jl. Wahid Hasyim No.175, Rw. V, Bapangan, Kec. Jepara, Kabupaten Jepara, Jawa Tengah 59413","Telepon (0291) 591175"))
                list.add(Hospital("RSUD Dr. Loekmonohadi Kudus","Alamat Jl. Dr. Lukmonohadi No. 19, Kudus","Telepon (0291) 444001"))
                list.add(Hospital("RSUD Sunan Kalijaga Demak","Alamat Jl. Sultan Fatah 669/50, Bintoro, Kecamatan Demak, Bogorame, Bintoro, Kec. Demak, Kabupaten Demak, Jawa Tengah 59511","Telepon (0291) 685018"))
                list.add(Hospital("RSUD dr. R. Soedjati Grobogan","Alamat Jl. D. I. Panjaitan No.36, Ngabean, Purwodadi, Kec. Purwodadi, Kabupaten Grobogan, Jawa Tengah 58111","Telepon (0292) 421004"))
                list.add(Hospital("RSUD Soehadi Prijonegoro Sragen","Alamat Sragen, Ngrandu, Nglorog, Kec. Sragen, Kabupaten Sragen, Jawa Tengah 57215","Telepon (0271) 891068"))
                list.add(Hospital("RS Fastabiq Sehat PKU Muhammadiyah Pati","Alamat Jl. Raya Pati - Tayu No.Km 3, Runting, Tambaharjo, Kec. Pati, Kabupaten Pati, Jawa Tengah 59119","Telp 4199008"))
                list.add(Hospital("RSUD RAA Soewondo Pati","Alamat Jl. Dr. Susanto No.114, Ngipik, Kutoharjo, Kec. Pati, Kabupaten Pati, Jawa Tengah 59111","Telepon (0295) 381102"))
                list.add(Hospital("RSUD Kota Surakarta","Alamat Kedungupit, Sawahan, Kec. Ngemplak, Kabupaten Boyolali, Jawa Tengah 57375","Telepon (0271) 715300"))
                list.add(Hospital("RS Kasih Ibu Surakarta","Alamat Jl. Slamet Riyadi No.404, Purwosari, Laweyan, Surakarta, Central Java 57142","Telepon (0271) 714422"))
                list.add(Hospital("Rumkit Tk. III/Slamet Riyadi Surakarta","Alamat Jl. Slamet Riyadi No No.321Kvi, Purwosari, Kec. Laweyan, Kota Surakarta, Jawa Tengah 57148","Telepon (0271) 714656"))
                list.add(Hospital("RS PKU Muhammadiyah Surakarta","Alamat Jl. Ronggowarsito No.130, Timuran, Kec. Banjarsari, Kota Surakarta, Jawa Tengah 57131","Telp (0271) 714 578"))
                list.add(Hospital("RS dr. Oen Surakarta","Alamat Jl. Brigjen Katamso No.55, Tegalharjo, Kec. Jebres, Kota Surakarta, Jawa Tengah 57128","Telepon (0271) 643139"))
                list.add(Hospital("RSU Dr. Moewardi","Alamat Jl. Kol. Sutarto 132, Surakarta","Telepon (0271) 637415"))
                list.add(Hospital("RSUD dr. R. Soetrasno Rembang","Alamat Jl. Pahlawan No.16, Kabongan Kidul, Kec. Rembang, Kabupaten Rembang, Jawa Tengah 59218","Telepon (0295) 691444"))
                list.add(Hospital("RSUD dr. R. Soetijono Blora","Alamat Jl. Dr. Sutomo No.42, Blora, Tempelan, Kec. Blora, Kabupaten Blora, Jawa Tengah 58219","Telepon (0296) 531118"))
            }
            "Jawa Timur" -> {
                list.add(Hospital("RSAU-3 DR. EFRAM HARSANA IWJ","Alamat Unnamed Road, Bakung, Maospati, Kec. Maospati, Kabupaten Magetan, Jawa Timur 63392","Telepon 0812-8333-9424"))
                list.add(Hospital("Rumkit Tk. IV/Madiun","Alamat Jl. Pahlawan No.79, Kartoharjo, Kec. Kartoharjo, Kota Madiun, Jawa Timur 63121","Telepon (0351) 454787"))
                list.add(Hospital("RS Dr Soedono","Alamat Jl. Dr. Sutomo No.59, Kartoharjo, Kec. Kartoharjo, Kota Madiun, Jawa Timur 63117","Telepon (0351) 464325 , 464326 , 454567"))
                list.add(Hospital("TK.III Tulungagung","Alamat Jl. I Gusti Ngurah Rai No.29, Bago, Kec. Tulungagung, Kabupaten Tulungagung, Jawa Timur 66218",""))
                list.add(Hospital("RSUD Dr. Iskak Tulungagung","Alamat Jl. Dr. Wahidin Sudiro Husodo Tulungagung","Telepon (0355) 322609"))
                list.add(Hospital("Tk II Kediri","Alamat Jl. Kombes Pol Duryat No.17, Dandangan, Kec. Kota Kediri, Kota Kediri, Jawa Timur 64129","Telepon (0354) 671100"))
                list.add(Hospital("Rumkit Tk. IV/Kediri","Alamat Jl. Mayjend Sungkono No.44, Semampir, Kec. Kota Kediri, Kota Kediri, Jawa Timur 64129","Telepon (0354) 687801"))
                list.add(Hospital("RSUD Kab. Kediri","Alamat Jl. Pahlawan Kusuma Bangsa No.1, Pare, Kediri","Telepon (0354) 391718"))
                list.add(Hospital("Tk III Nganjuk","Alamat Jl. Abdurahman Saleh VI No.56, Kauman, Kec. Nganjuk, Kabupaten Nganjuk, Jawa Timur 64411","Telepon (0358) 321896"))
                list.add(Hospital("Tk III Bojonegoro","Alamat Jl. Panglima Sudirman No.160, Klangon, Kec. Bojonegoro, Kabupaten Bojonegoro, Jawa Timur 62113","Telepon (0353) 888780"))
                list.add(Hospital("RS Dr R Koesma Tuban","Alamat Jl. Dr. WS Husodo, Tuban","Telepon (0356) 321010 , 325696 , 323266"))
                list.add(Hospital("RS Muhammadiyah Lamongan","Alamat Jl. Jaksa Agung Suprapto 76 Lamongan 62215","Telp (0322) 322834 , 08123082211 , 082257622453"))
                list.add(Hospital("Tk III Batu Malang","Alamat Ngaglik, Kec. Batu, Kota Batu, Jawa Timur 65311","Telepon (0341) 591067"))
                list.add(Hospital("RS Univ Muhammadiyah Malang","Alamat Jl. Raya Tlogomas No. 45 Kel. Tlogomas, Kec. Lowokwaru - Malang 65144","Telp (0341) 561666 , 087859923678"))
                list.add(Hospital("Rumkit Tk. II/Soepraoen Malang","Alamat Jl. S. Supriadi No.22, Sukun, Kec. Sukun, Kota Malang, Jawa Timur 65112","Telepon (0341) 325112"))
                list.add(Hospital("RSU Dr. Saiful Anwar","Alamat Jl. Jaksa Agung Suprapto No. 2, Malang","Telepon 0341 362101"))
                list.add(Hospital("RSAU-3 DR. M. MUNIR LANUD ABD","Alamat Komplek TNI AU, Jl. Dr. Munir No. 18, Saptorenggo, Pakis, Krajan, Saptorenggo, Kec. Pakis, Malang, Jawa Timur 65154","Telepon (0341) 792273"))
                list.add(Hospital("Tk. III Pusdik Brimob Watukosek","Alamat Jl. Raya Watukosek, Watukosek, Gempol, Wates, Watukosek, Kec. Gempol, Pasuruan, Jawa Timur 67155","Telepon (0343) 856965"))
                list.add(Hospital("Tk III Pusdik Gasum","Alamat Jl. Raya Porong No.1, Porong, Kec. Porong, Kabupaten Sidoarjo, Jawa Timur 61274","Telepon (0343) 856444"))
                list.add(Hospital("RSUD Sidoarjo","Alamat Jl. Mojopahit No.667, Sidowayah, Celep, Kec. Sdioarjo, Kab.Sidoarjo","Telepon (031) 8961649"))
                list.add(Hospital("RUMKITBAN SIDOARJO","Alamat Jl. Dr. Soetomo No.2, Gajah Timur, Magersari, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61212","Telepon (031) 8964610"))
                list.add(Hospital("RS Siti Khotijah Sepanjang - Sidoarjo","Alamat Jl. Pahlawan no 260 Sepanjang Sidoarjo 61257 - Jawa Timur","Telp (031) 7882123 , 7881130 , 08113336767"))
                list.add(Hospital("Tk II Surabaya","Alamat Jl. Ahmad Yani No.116, Ketintang, Kec. Gayungan, Kota SBY, Jawa Timur 60231","Telepon (031) 8292227"))
                list.add(Hospital("RSAL-3 EWA PANGALILA (RS Marinir)","Alamat Gn. Sari, Kec. Dukuhpakis, Kota SBY, Jawa Timur 60224","Telepon (031) 5682405"))
                list.add(Hospital("Rumkit Tk. III/Brawijaya/Surabaya","Alamat Jl. Kesatriyan No.17, Sawunggaling, Kec. Wonokromo, Kota SBY, Jawa Timur 60242","Telepon (031) 5670650"))
                list.add(Hospital("RSPAL-1 dr RAMELAN","Alamat Jl. Gadung No.1, Jagir, Kec. Wonokromo, Kota SBY, Jawa Timur 60244","Telepon (031) 8438153"))
                list.add(Hospital("RSAU-4 DR. SOEMITRO LANUD MUL SBY","Alamat Jl. Serayu No.17, Darmo, Kec. Wonokromo, Kota SBY, Jawa Timur 60241, Indonesia","Telepon (031) 5669514"))
                list.add(Hospital("RS Universitas Airlangga","Alamat Kampus C Universitas Airlangga, Mulyorejo, Surabaya","Telepon (031) 5916290 , 5916287 , 58208290"))
                list.add(Hospital("RSAL-3 OEPOMO","Alamat Jl. Laksda Moh. Nazir No.56, Perak Utara, Kec. Pabean Cantian, Kota SBY, Jawa Timur 60177",""))
                list.add(Hospital("Balai Teknik Kesehatan Lingkungan dan Pengendalian Penyakit Surabaya","Alamat Jl. Sidoluhur No.12, Kemayoran, Kec. Krembangan, Kota SBY, Jawa Timur 60175","Telepon (031) 3540189"))
                list.add(Hospital("RUMKITBAN SURABAYA","Alamat Jl. Gubeng Pojok No.21, Ketabang, Kec. Genteng, Kota SBY, Jawa Timur 60272","Telepon (031) 5310069"))
                list.add(Hospital("Fakultas Kedokteran Universitas Airlangga","Alamat Jl. Mayjen Prof. Dr. Moestopo No.47, Pacar Kembang, Kec. Tambaksari, Kota SBY, Jawa Timur 60132",""))
                list.add(Hospital("RSU Dr. Soetomo","Alamat Jl. Prof. Dr. Moestop No. 6-8, Surabaya","Telepon (031) 5501001 , 5501239"))
                list.add(Hospital("Balai Besar Laboratorium Kesehatan Surabaya","Alamat Jl. Karang Menjangan No.18, Airlangga, Kec. Gubeng, Kota SBY, Jawa Timur 60286","Telepon (031) 5020306"))
                list.add(Hospital("Tk III Lumajang","Alamat Jl. Kapten Kyai Ilyas No.7, Tompokersan, Kec. Lumajang, Kabupaten Lumajang, Jawa Timur 67316","Telepon (0334) 881646"))
                list.add(Hospital("Rumkit Tk. III/Baladika Husada/Jember","Alamat Jl. PB Sudirman No.45, Pagah, Jemberlor, Kec. Patrang, Kabupaten Jember, Jawa Timur 68118","Telepon (0331) 482541"))
                list.add(Hospital("RSU Dr. Soebandi","Alamat Jl. Dr. Soebandi No. 124 Kel.Patrang, Jember 68111","Telepon (0331) 487441"))
                list.add(Hospital("Tk III Bondowoso","Alamat Jalan Jend. Pol. S. Judhodiharjo No.12, Purbosari, Blindungan, Bondowoso, Bondowoso Regency, East Java 68219","Telepon (0332) 433431"))
                list.add(Hospital("RSUD Blambangan","Alamat Jl. Letkol Istiqlah No.49, Singonegaran, Kec. Banyuwangi, Kabupaten Banyuwangi, Jawa Timur 68415","Telepon (0333) 421118 , 421071"))
                list.add(Hospital("RS Fatimah Banyuwangi","Alamat Jl. Jember No. 25 Kalirejo, Kabat, Banyuwangi, Jawa Timur 68461","Telp (0333) 421451"))
            }
            "Bali" -> {
                list.add(Hospital("BRSU Tabanan Bali","Alamat Jl. Pahlawan No.14 Tabanan Bali","Telepon (0361) 811027 , 819810 , 811202"))
                list.add(Hospital("RSU Sanjiwani Gianyar","Alamat Jl. Ciung Wenara No. 2, Gianyar","Telepon (0361) 943049"))
                list.add(Hospital("Tk III Trijatra Denpasar","Alamat Jl. Trijata No. 32, Sumerta Kelod 2F, Kelod, Dangin Puri Kangin, Denpasar Timur, Dangin Puri Kangin, Kec. Denpasar Utara, Kota Denpasar, Bali 80233","Telepon (0361) 234670"))
                list.add(Hospital("Rumkit Tk. II/Udayana Denpasar","Alamat Jl. Jend. Sudirman No.1, Dangin Puri Klod, Kec. Denpasar Tim., Kota Denpasar, Bali 80232","Telepon (0361) 228068RSUP Sanglah Denpasar"))
                list.add(Hospital("RSUP Sanglah Denpasar","Alamat Jl. Diponegoro Denpasar, Bali","Telepon (0361) 227911 - 15"))
            }
        }

        return list
    }
}